### PR TITLE
Merge fixes for issues #5, #6, #7, #9, #14, #15, #17

### PR DESCRIPTION
**Pull request by thenewguy**
I merged my commits for issues #5, #6, #7, #9, #14, #15, #17 into one pull request because there were merge conflicts

### CODE REVIEW

**Comment by thenewguy** [comment]
e57e21d3163a21e2658b90b878d220f0b6c00466 is a backwards compatible fix for #14

**Comment by nielsvanoch** [comment]
Thanks for the hard work! I'm going to look into all of your pull requests this weekend.

**Comment by thenewguy** [comment]
Sounds good.  There is one issue I am not sure how to go about fixing without knowing more about the projects compatibility requirements... it doesn't feel right to expose an AutoID field value to the client so it would be very beneficial to use UUID primary keys for the Lock model to allow their use in the front end.  

Because of the nature of locks and how the interaction interface is written, I don't think it would be very disruptive to migrate from an AutoField id to a UUIDField id.

Would you be opposed to changing the primary key field type and the minimum supported version of django after a version bump?

**Comment by nielsvanoch** [comment]
That's something I would be ok with, and our requirements allow for it. Feel free to make a proposal!

I merged all of your changes into version 1.1.0, together with some additional changes we had pending. It required a bit of merge magic, but this pull request is in there.

**Pull request closed without merging**
