### PR TITLE
Update management command to use correct import

### PR DESCRIPTION
**Pull request by pieterdd**

### CODE REVIEW

**Comment by nielsvanoch** [comment]
This looks good. I'm releasing a new version today, I'll merge this in.

**Comment by nielsvanoch** [comment]
This was already fixed in the latest master.

**Comment by pieterdd** [comment]
What about the unit test?

**Comment by nielsvanoch** [comment]
https://github.com/vikingco/django-db-locking/blob/master/locking/tests.py#L128

**Comment by pieterdd** [comment]
Oh shoot, sorry.

**Pull request closed without merging**
